const path = require("path");

/** @type {import('next').NextConfig} */
const nextConfig = {
  outputFileTracingRoot: path.join(__dirname, "../.."),
  transpilePackages: [
    "@next-ui/core",
    "@next-ui/utils",
    "@next-ui/theme",
    "@next-ui/responsive",
    "@next-ui/button",
    "@next-ui/card",
    "@next-ui/input",
    "@next-ui/badge",
    "@next-ui/avatar",
    "@next-ui/modal",
    "@next-ui/tabs",
    "@next-ui/toast",
    "@next-ui/tooltip",
    "@next-ui/select",
    "@next-ui/switch",
    "@next-ui/checkbox",
    "@next-ui/slider",
    "@next-ui/progress",
    "@next-ui/table",
    "@next-ui/navbar",
    "@next-ui/breadcrumbs",
    "@next-ui/link",
    "@next-ui/pagination",
    "@next-ui/chip",
    "@next-ui/accordion",
    "@next-ui/alert",
    "@next-ui/drawer",
    "@next-ui/textarea",
    "@next-ui/divider",
    "@next-ui/spacer",
    "@next-ui/code",
    "@next-ui/skeleton",
    "@next-ui/spinner",
  ],
};
module.exports = nextConfig;
